apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engine-module-25017
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/engine-module-25017
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
